<?php
/**
 * @var \Cubex\View\Layout $this
 */
?>
<!--  Navbar-->
<div class="navbar navbar-static-top navbar-inverse">
  <div class="navbar-inner" id="sidekick-header">
    <div class="container">
      <a class="muted brand" href="/">Sidekick</a>
      <?php echo $this->renderNest("header"); ?>

      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><a href="/profile">John Doe</a></li>
          <li><a href="/logout">Logout</a></li>
        </ul>

      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<!--Navbar-->

<div id="sidekick-page">
  <div id="sidekick-main">
    <?php echo $this->renderNest("sidebar"); ?>
    <div id="sidekick-content">
      <?php echo $this->renderNest("content"); ?>
      <div class="clearfix"></div>
    </div>
  </div>

  <div id="footer">
    <div class="container">
      <?php echo $this->renderNest("footer", false); ?>
    </div>
  </div>
</div>
