<?php
/**
 * @var \Cubex\View\Layout $this
 */
?>
<!--  Navbar-->
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner" id="sidekick-header">
    <div class="container">
      <?php echo $this->renderNest("header"); ?>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<!--Navbar-->

<div id="sidekick-page" class="container">
  <div id="sidekick-main">
    <?php echo $this->renderNest("sidebar"); ?>
    <div id="sidekick-content">
      <?php echo $this->renderNest("content"); ?>
      <div class="clearfix"></div>
    </div>
  </div>

  <div id="footer">
    <div class="container">
      <?php echo $this->renderNest("footer", false); ?>
    </div>
  </div>
</div>
